---
- name: Delete k8s cluster
  hosts: k8s_ws
  become: yes
  vars:
    cluster_name: "prod.k8s.local"
    state_store: "k8-bucket-abi8971"
  tasks:
    - name: Delete Kubernetes cluster
      command: >
        kops delete cluster
        --name {{ cluster_name }}
        --state s3://{{ state_store }}
        --yes
      when: delete_cluster is defined and delete_cluster | bool
      register: kops_delete_cluster
    - name: Output the result of the cluster deletion
      debug:
        var: kops_delete_cluster.stdout
      when: delete_cluster is defined and delete_cluster | bool
...