---
- name: Deploy Calculator App to Kubernetes
  hosts: k8s_ws
  become: yes
  tasks:
    - name: Apply deployment manifest
      kubernetes.core.k8s:
        kubeconfig: /root/.kube/config
        state: present
        src: ../k8s/deployment.yaml
...